configfile: "config/config.yaml"

import os
import pandas as pd
import yaml
import logging




RESDIR = config["outputdir"]
BINS = config["genome_input"]

DBFILE = config["dbfile"]


 
# anviodbs = utils.get_anvio_db_path()
        

if not BINS:
    wlogger.error("Can't retrieve your bins :( you might check your input or the genome extension.")
    exit(-1)   

rule anvio_estimate:
    input:
        expand(
            os.path.join(RESDIR, "anvio.{table}.tsv"),
            table = ["completness", "classify"]
        )

rule anvio_expand_scg_taxonomy:
    output:
        os.path.join(RESDIR, "anvio.{table}.tsv"),
    input:
        expand(os.path.join(RESDIR , "{bin}" , "anvio.{{table}}.tsv"),bin=BINS.keys()),
    shell:
        "head -n 1 {input[0]} > {output} && tail -n +2 -q {input} >> {output}"

rule anvio_scg_completness:
    output:
        temp(os.path.join(RESDIR , "{bin}" , "anvio.completness.tsv")),
    input:
        os.path.join(RESDIR , "{bin}" , "CONTIGS.db"),        
    conda:
        "envs/anvio-7.1.yaml"
    shell:
        "anvi-estimate-genome-completeness -c {input} -o {output}"


rule anvio_scg_taxonomy:
    output:
        temp(os.path.join(RESDIR , "{bin}" , "anvio.classify.tsv")),
    input:
        os.path.join(RESDIR , "{bin}" , "CONTIGS.db"),        
    params:        
        scgdir  = "--scgs-taxonomy-data-dir {}".format(anviodbs) if anviodbs else "",            
    threads:
        10
    conda:
        "envs/anvio-7.1.yaml"
    shell:
        "anvi-run-scg-taxonomy {params.scgdir} -c {input} -T {threads} && "
        "anvi-estimate-scg-taxonomy -c {input} -o {output}"

rule anvio_contig_db:
    output:
        db = temp(os.path.join(RESDIR , "{bin}" , "CONTIGS.db")),
        tmp = temp(os.path.join(RESDIR , "{bin}" , "CONTIGS.fasta")),
    input:
        lambda wildcards: BINS[wildcards.bin],
    conda:
        "envs/anvio-7.1.yaml"
    threads:
        10
    shell:
        "anvi-script-reformat-fasta -o {output.tmp} --simplify-names {input} ; "
        "anvi-gen-contigs-database -n {wildcards.bin} -T {threads} -f {output.tmp} -o {output.db} -n {wildcards.bin} ; "
        "anvi-run-hmms -c {output.db} --just-do-it -T {threads}"
         