ASSEMBLER:
- megahit
- unicycler
- spades
ASSEMBLY_TYPES:
- short_reads
INPUT: /Users/mmillet/Documents/src/workflows/assembly-dataset.yaml
KLIST: 21,33,55,77,99
MEGAHIT: null
MODE: single
NAME: MGW
RESDIR: /Users/mmillet/Documents/src/workflows
SNAKARGS: --dry-run
SPADES: null
UNICYCLER: null
min_identity: 95
min_len: 100
min_quality: 20
properly_paired: true
