#CM stand to CheckM - this suffix avoid duplicated keys between worfklow (e.g, batch_size checkM / batch_size GTDB)
genome_input : 'test/genomes.yaml'
res_dir : test/results
CheckM_data : null

taxonomy_wf:
  enable: FALSE
  rank : ""
  taxon : ""
  
batch_size : 1000
genome_extension : "fna.gz"
low_memory : True