input: null
input.conf:
  required: True
  help: 'yaml file containg path to genomes (genome_label: genome_path)' 
  type: 'str'

output : "moose-res/genomes/dereplication"

length: 50000
length.conf:
  help: minimum genome length

completness: 75  
completness.conf:
  help: minimum genome completeness

contamination: 25
contamination.conf:
  help: maxium genome contamination

ignore_quality: False
ignore_quality.conf:
  help: don't filter genomes based on quality

qual_info: null
qual_info.conf:
  help: Don't run checkm with dRep but instead use the file provided to this option

primary_ani: 0.95
primary_ani.conf:
  help: First clustering ANI threshold

secondary_ani: 0.99
secondary_ani.conf:
  help: Second clustering ANI threshold
   
coverage: 0.1
coverage.conf:
  help: Minimum level of overlap for secondary clustering

multiround: False