input: null
input.conf:
  required: True
  help: 'yaml file containg path to genomes (genome_label: genome_path)' 
  type: 'str'

output : "moose-res/genomes/classify"

# merge_with: null

gtdb : null
gtdb.conf:
  required: True
  type: 'str'

batch_size : 1000

GTDB_isani: False

GTDB_mash:
  k : 16
  s : 5000
  d : 0.1 
  v : 1.0

GTDB_fa_min_af : 0.65