input : ""
input.conf:
  required: True
  help: 'yaml file containg path to genomes (genome_label: genome_path)' 
  type: 'str'

output : moose-res/genomes/quality
output.conf:
  help: 'output directory'
  

checkm_data: null
checkm_data.conf:
  required: True
  help: 'path to checkm datas'
  type: 'str'

taxonomy_wf:
  enable: FALSE
  rank : ""
  taxon : ""
  
batch_size : 1000
low_memory : True